a= input('digite um algo')
print ('o tipo primitivo desse valor é', type(a))
print ('so tem espaços ? ', a .isspace())
print ('e numerico ?', a.isnumeric())
print ('e alfabetico ?', a.isalpha())
print ('e decimal ?', a.isdecimal())
print ('foi ou e digitavel ?',a.isdigit())
print ('e alpha anumerico ?',a.isalnum())
print ('e indentificavel ?', a.isidentifier())
print ('e Impresso ?', a.isprintable())
print ('e um espaço ?', a.isspace())
print ('esta capitalizada ?', a.istitle())
print ('esta em minusculas ?', a.islower())
print ('esta em maisculas ?', a.isupper())