a= input('digite um algo')

print (f'o tipo primitivo desse valor é {type(a)}')
print (f'so tem espaços ? {a.isspace()}')
print (f'e numerico ? {a.isnumeric()}')
print (f'e alfabetico ? {a.isalpha()}')
print (f'e decimal ? {a.isdecimal()}')
print (f'foi ou e digitavel ? {a.isdigit()}')
print (f'e alpha anumerico ? {a.isalnum()}')
print (f'e indentificavel ? {a.isidentifier()}')
print (f'e Impresso ? {a.isprintable()}')
print (f'e um espaço ? {a.isspace()}')
print (f'esta capitalizada ?  {a.istitle()}')
print (f'esta em minusculas ? {a.islower()}')
print (f'esta em maisculas ? {a.isupper()}')